import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Footer from './Footer';

interface Props {
  title: string;
  children: any;
}
export default function Layout({ title, children }: Props) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        {/* <link rel='icon' href='/favicon.ico' /> */}
        <link
          rel='apple-touch-icon'
          sizes='180x180'
          href='/apple-touch-icon.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='32x32'
          href='/favicon-32x32.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='16x16'
          href='/favicon-16x16.png'
        />
        <link rel='manifest' href='/site.webmanifest' />
        <link rel='mask-icon' href='/safari-pinned-tab.svg' color='#5bbad5' />
        <meta name='msapplication-TileColor' content='#da532c' />
        <meta name='theme-color' content='#ffffff'></meta>
      </Head>

      <div className='min-h-screen w-full dark:bg-black-one dark:text-white '>
        <Navbar />
        <main className='font-poppins container max-w-4xl mx-auto px-8 pb-8'>
          {children}
          <Footer />
        </main>
      </div>
    </>
  );
}
